[package]
name = "critical-section"
version = "0.2.7"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"
description = "Critical section abstraction"
repository = "https://github.com/embassy-rs/critical-section"
readme = "README.md"
license = "MIT OR Apache-2.0"
categories = [
    "embedded",
    "no-std",
    "concurrency",
]

[features]
custom-impl = []

[dependencies]
bare-metal = "1.0.0"
cfg-if = "1.0.0"

[target.'cfg(target_arch = "riscv32")'.dependencies]
riscv = {version = "0.7.0"}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
